GET http://localhost:5000/todos

###

POST http://localhost:5000/todo/new
Content-Type: application/json

{
    "text": "Order Pizza"
}

###

DELETE http://localhost:5000/todo/delete/626d3a5a3c42d86997571e0b

###

PUT http://localhost:5000/todo/complete/626d3a0c3c42d86997571e09